apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
  - name: mysql-container
    image: 634809228531.dkr.ecr.us-east-1.amazonaws.com/db_mysql:v0.1
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
      imagePullSecrets:
          - name: regcred