apiVersion: v1
kind: Pod
metadata:
  name: application
  labels:
    app: employees
    component: frontend
spec:
  containers:
    - name: websrv-images
      image: 634809228531.dkr.ecr.us-east-1.amazonaws.com/webapp:v0.4
      env:
        - name: DBPWD
          value: Temp/123
        - name: DBUSER
          value: root
        - name: DBHOST
          value: "mysql.database.svc.cluster.local"
        - name: DBPORT
          value: "3306"
      ports:
        - containerPort: 8080
