apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: application
  labels:
    app: employees
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      component: frontend
  template:
    metadata:
      labels:
        app: employees
        component: frontend
    spec:
      containers:
        - name: employees-images
          image: 634809228531.dkr.ecr.us-east-1.amazonaws.com/webapp:v0.2
          env:
          - name: DBPWD
            value: Temp/123
          - name: DBUSER
            value: root
          - name: DBHOST
            value: "mysql.database.svc.cluster.local"
          - name: DBPORT
            value: "3306"
          ports:
            - containerPort: 8080
